### ISSUE TITLE
Complete manual for v4.3.4

### ISSUE THREAD

**Issue by NurislamSheih** [sortmerna/sortmerna#315]
Hello,

I'm trying to run your tool to filter my data from rRNA sequences, but I can't find the manual for the latest sortmerna release. Could you please attach a PDF file?

**Comment by biocodz** [comment]
Yeah, that's a weak part of the project still waiting for improvement.

**Comment by SergeyBaikal** [comment]
Dear developers, is there still no manual?

**Comment by ekopylova** [comment]
Hello @SergeyBaikal ,

Very good point. Indeed, we don't have an updated manual yet, I will write some quick examples on GitHub next week.

I'll let @biocodz give you some suggestions on where you can get details on how to run the program (we have many tests for running the tool with many examples).

Thanks for bringing it up!
Jenya

**Comment by SergeyBaikal** [comment]
Thank you very much for your answer Jenya!

**Comment by cmith44** [comment]
@NurislamSheih @SergeyBaikal Closing this issue. For all discussion about documentation, please see #329.

**Comment by cmith44** [comment]
We have started working on SortMeRNA's documentation, and have setup a [Read The Docs page](https://sortmerna.readthedocs.io/en/latest/index.html). For now, the information in the GitHub wiki has been copied to the RTD project, but we plan to rearrange, update, and clean the documentation in the following weeks. 

@biocodz Since we've copied the contents of the wiki to the RTD project, do you mind if I delete the wiki and make it redirect to Read The Docs so we can setup a centralised SortMeRNA documentation?
